<?php
/**
 * Site footer and closing scripts. Accepts optional $page['scripts'] (array of paths under assets/).
 */
?>
    </main>

    <!-- footer start -->
    <footer>
        <img src="<?= asset('images/template/background/8.svg') ?>" class="img-fluid footer-top-effect" alt="">
        <div class="container">
            <div class="row g-4">
                <div class="col-md-5">
                    <div class="footer-info">
                        <a href="<?= url() ?>" class="d-inline-block mb-4" aria-label="<?= e(SITE_NAME) ?> - Inicio">
                            <?= brand_logo('light') ?>
                        </a>
                        <p>Expediente clínico electrónico y gestión integral del consultorio, en la nube y pensado para México.</p>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="footer-col">
                        <div class="footer-links">
                            <h3 class="footer-title"><?= e(SITE_NAME) ?></h3>
                            <ul class="footer-content">
                                <?php foreach (MAIN_NAV as $slug => $label): ?>
                                    <li><a href="<?= url($slug) ?>"><?= e($label) ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="footer-links">
                            <h3 class="footer-title"><?= e(COMPANY_NAME) ?></h3>
                            <ul class="footer-content">
                                <li><a href="<?= url('contact') ?>">Contacto</a></li>
                                <li><a href="mailto:<?= e(CONTACT_EMAIL) ?>"><?= e(CONTACT_EMAIL) ?></a></li>
                                <li><a <?= whatsapp_link_attributes() ?>>WhatsApp <?= e(WHATSAPP_DISPLAY) ?></a></li>
                            </ul>
                        </div>
                        <div class="footer-links">
                            <h3 class="footer-title">Legal</h3>
                            <ul class="footer-content">
                                <?php foreach (LEGAL_NAV as $slug => $label): ?>
                                    <li><a href="<?= url($slug) ?>"><?= e($label) ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-sec">
                <p>© <?= date('Y') ?> <?= e(COMPANY_NAME) ?>. Todos los derechos reservados.</p>
                <p><?= e(SITE_NAME) ?> es un producto de <?= e(COMPANY_NAME) ?>.</p>
            </div>
        </div>
    </footer>
    <!-- footer end -->

    <a <?= whatsapp_link_attributes() ?> class="whatsapp-float" aria-label="Escríbenos por WhatsApp">
        <?= whatsapp_icon() ?>
        <span class="whatsapp-float-label">¿Hablamos por WhatsApp?</span>
    </a>

    <button type="button" id="backToTop" class="back-to-top" aria-label="Volver arriba">
        <i data-lucide="move-up"></i>
    </button>

    <!-- Vendor scripts (defer keeps execution order and avoids blocking rendering) -->
    <script src="<?= asset('js/vendor/bootstrap.min.js') ?>" defer></script>
    <script src="<?= asset('js/vendor/gsap.min.js') ?>" defer></script>
    <script src="<?= asset('js/vendor/ScrollTrigger.min.js') ?>" defer></script>
    <script src="<?= asset('js/vendor/split-type.js') ?>" defer></script>
    <script src="<?= asset('js/vendor/aos.js') ?>" defer></script>
    <script src="<?= asset('js/vendor/lenis.min.js') ?>" defer></script>

    <!-- Site scripts. icons.js is generated by tools/build-icons.js. -->
    <script src="<?= asset('js/icons.js') ?>" defer></script>
    <script src="<?= asset('js/main.js') ?>" defer></script>
    <?php foreach ($page['scripts'] ?? [] as $script): ?>
        <script src="<?= asset($script) ?>" defer></script>
    <?php endforeach; ?>
</body>

</html>
