/**
 * Builds assets/js/icons.js with only the Lucide icons used by the site.
 *
 * The full Lucide bundle (tools/vendor/lucide.js, ~600 KB) is only read here and is not part of the site.
 * Run it again whenever you add or change an icon:
 *
 *     node tools/build-icons.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.join(ROOT, "assets/js/icons.js");
const SOURCE_DIRS = [".", "includes", "assets/js"];
const IGNORED_FILES = new Set(["icons.js"]);

// Icon references: data-lucide="name" in markup and 'icon' => 'name' in PHP content arrays.
const ICON_PATTERNS = [/data-lucide="([a-z0-9-]+)"/g, /'icon'\s*=>\s*'([a-z0-9-]+)'/g];

const toPascalCase = (name) => name.replace(/(^|-)([a-z0-9])/g, (_, __, char) => char.toUpperCase());

const findIconNames = () => {
  const names = new Set();

  SOURCE_DIRS.forEach((dir) => {
    fs.readdirSync(path.join(ROOT, dir))
      .filter((file) => /\.(php|js)$/.test(file) && !IGNORED_FILES.has(file))
      .forEach((file) => {
        const content = fs.readFileSync(path.join(ROOT, dir, file), "utf8");
        ICON_PATTERNS.forEach((pattern) => {
          for (const match of content.matchAll(pattern)) names.add(match[1]);
        });
      });
  });

  return [...names].sort();
};

const { icons } = require(path.join(__dirname, "vendor/lucide.js"));
const names = findIconNames();
const subset = {};

names.forEach((name) => {
  const icon = icons[toPascalCase(name)];
  if (!icon) {
    console.error(`Icon not found in Lucide: ${name}`);
    process.exitCode = 1;
    return;
  }
  subset[name] = icon;
});

const output = `/* Generated by tools/build-icons.js - do not edit by hand. Lucide icons (ISC license). */
(() => {
  const ICONS = ${JSON.stringify(subset)};

  const SVG_NS = "http://www.w3.org/2000/svg";
  const DEFAULT_ATTRIBUTES = {
    xmlns: SVG_NS,
    width: 24,
    height: 24,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    "stroke-width": 2,
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
  };

  const createNode = ([tag, attributes, children]) => {
    const node = document.createElementNS(SVG_NS, tag);
    Object.entries(attributes).forEach(([key, value]) => node.setAttribute(key, String(value)));
    (children || []).forEach((child) => node.appendChild(createNode(child)));
    return node;
  };

  /** Replaces every <i data-lucide="name"> with its inline SVG, keeping the element's attributes. */
  const createIcons = () => {
    document.querySelectorAll("[data-lucide]").forEach((element) => {
      if (element.tagName.toLowerCase() === "svg") return;

      const name = element.getAttribute("data-lucide");
      const icon = ICONS[name];
      if (!icon) {
        console.warn(\`Icon "\${name}" is not in icons.js. Run: node tools/build-icons.js\`);
        return;
      }

      const ownAttributes = Object.fromEntries([...element.attributes].map((attr) => [attr.name, attr.value]));
      const isLabelled = Object.keys(ownAttributes).some((key) => key.startsWith("aria-") || key === "role" || key === "title");
      const className = ["lucide", \`lucide-\${name}\`, ownAttributes.class].filter(Boolean).join(" ");

      const svg = createNode([
        "svg",
        { ...DEFAULT_ATTRIBUTES, ...(isLabelled ? {} : { "aria-hidden": "true" }), ...ownAttributes, class: className },
        icon,
      ]);
      element.replaceWith(svg);
    });
  };

  window.lucide = { createIcons };
})();
`;

fs.writeFileSync(OUTPUT, output);
console.log(`icons.js: ${names.length} icons, ${(Buffer.byteLength(output) / 1024).toFixed(1)} KB`);
